<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Amber Gunter">

<title>Assignment Design</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Assignment Design_files/libs/clipboard/clipboard.min.js"></script>
<script src="Assignment Design_files/libs/quarto-html/quarto.js"></script>
<script src="Assignment Design_files/libs/quarto-html/popper.min.js"></script>
<script src="Assignment Design_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Assignment Design_files/libs/quarto-html/anchor.min.js"></script>
<link href="Assignment Design_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Assignment Design_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Assignment Design_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Assignment Design_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Assignment Design_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Assignment Design</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Amber Gunter </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="section-1" class="level1">
<h1>Section 1</h1>
<section id="irrigation-and-fertilizer" class="level2">
<h2 class="anchored" data-anchor-id="irrigation-and-fertilizer">Irrigation and Fertilizer</h2>
<ol type="1">
<li><p><strong>Identify the design:</strong> Split plot -design</p></li>
<li><p><strong>Identify the main plot and subplot factors (if applicable):</strong> main plot is the irrigation method and subplot is the fertilizer type</p></li>
<li><p><strong>Identify the experimental and observational unit for each factor:</strong> For irrigation method, the experimental unit is the field (because its applied to the whole field) and the observational unit is the plot. For the fertilizer type, the experimental unit and the observational unit are both the plot within the field.</p></li>
<li><p><strong>Write either:</strong></p>
<ol type="1">
<li><p><strong>A linear model equation or</strong></p></li>
<li><p><strong>An ANOVA model equation:</strong></p></li>
</ol>
<p><span class="math display">\[
Y_{ijk}+\mu+\alpha_i+\beta_{ij}+\gamma_k+(\alpha\gamma)_{ik} +\epsilon_{ijk}
\]</span></p></li>
</ol>
<p>Where mu is the overall mean, alpha_i is the effect of irrigation method i, beta_ji is a random error due to field j nested in irrigation i (main plot error), gamma_k is the effect of fertilizer k, alpha x gamma_ik is the interaction between irrigation and fertilizer, and epsilon_ijk is the random subplot error.</p>
</section>
<section id="chick-feed-and-temperature" class="level2">
<h2 class="anchored" data-anchor-id="chick-feed-and-temperature">Chick Feed and Temperature</h2>
<ol type="1">
<li><p><strong>Identify the design:</strong> split plot design</p></li>
<li><p><strong>Identify the main plot and subplot factors (if applicable):</strong> The main plot is the feed type (standard vs.&nbsp;high-protein) applied to the whole pen, and the subplot factor is temperature (cool vs.&nbsp;warm) that is applied to cages within pens.</p></li>
<li><p><strong>Identify the experimental and observational unit for each factor:</strong> For feed type, the experimental unit is the pen, and the observation unit is the chicken. For temperature, the experimental unit is the cage within the pen, and the observational unit is the chicken (assuming based on the information given that we are weighing individual chickens).</p></li>
<li><p><strong>Write either:</strong></p>
<ol type="1">
<li><p><strong>A linear model equation or</strong></p></li>
<li><p><strong>An ANOVA model equation</strong></p>
<p><span class="math display">\[
Y_{ijk}=\mu+\alpha_i+\gamma_k+(\alpha\gamma)_ik+\epsilon_{ijk}
\]</span></p></li>
</ol></li>
</ol>
<p>Where mu is the overall mean, alpha_i is the effect of feed type, beta_ji is a random effect of pen nested in feed type, gamma_k is the effect of temperature,, alpha x gamma_ik is the interaction between feed type and temperature, and epsilon_ijk is the subplot error.</p>
</section>
<section id="plant-genotypes" class="level2">
<h2 class="anchored" data-anchor-id="plant-genotypes">Plant Genotypes</h2>
<ol type="1">
<li><p><strong>Identify the design:</strong> This is a randomized complete block design.</p></li>
<li><p><strong>Identify the main plot and subplot factors (if applicable).</strong> N/A</p></li>
<li><p><strong>Identify the experimental and observational unit for each factor.</strong> The experimental unit for the genotype factor is the plot within a block, and its the same for observation unit since yield is recorded per plot.</p></li>
<li><p><strong>Write either:</strong></p>
<ol type="1">
<li><p><strong>A linear model equation or</strong></p></li>
<li><p><strong>An ANOVA model equation</strong></p>
<p><span class="math display">\[
Y_{ij} = \mu+\alpha_i+\beta_j+\epsilon_{ij}
\]</span></p></li>
</ol></li>
</ol>
<p>Where mu is the overall mean, alpha_i is the fixed effect of genotype, beta_j is a random effect of block since there are soil differences, and epsilon_ij is the residual error term.</p>
</section>
<section id="weight-of-chickens" class="level2">
<h2 class="anchored" data-anchor-id="weight-of-chickens">Weight of Chickens</h2>
<ol type="1">
<li><p><strong>Identify the design</strong>: repeated measures design</p></li>
<li><p><strong>Identify the main plot and subplot factors (if applicable).</strong> N/A</p></li>
<li><p><strong>Identify the experimental and observational unit for each factor.</strong> For the fixed effect of diet, the experimental unit is the chick, and the observational unit is each time point per chick.</p></li>
<li><p><strong>Write either:</strong></p>
<ol type="1">
<li><p><strong>A linear model equation or</strong></p>
<p><span class="math display">\[
Y_{ijk}=\mu+\alpha_i+\gamma_k+(\alpha\gamma)_{ik}+b_j+\epsilon_{ijk}
\]</span></p>
<p>Where mu is the overall mena, alhpa_i is the fixed effect of diet, gamma_k is the fixed effect of week, alpha x gamma_ik is the interaction between diet and week, b_j is the random effect for chick and epsilon_ijk is the residual error term.<br>
</p></li>
<li><p><strong>An ANOVA model equation</strong></p></li>
</ol></li>
</ol>
</section>
<section id="soil-type-and-watering-frequency" class="level2">
<h2 class="anchored" data-anchor-id="soil-type-and-watering-frequency">Soil Type and Watering Frequency</h2>
<ol type="1">
<li><p><strong>Identify the design:</strong> Completely randomized design</p></li>
<li><p><strong>Identify the main plot and subplot factors (if applicable).</strong> N/A</p></li>
<li><p><strong>Identify the experimental and observational unit for each factor:</strong> experimental unit and observation units are both the pot because the entire treatment is applied to the pot and height is measured once per pot.</p></li>
<li><p><strong>Write either:</strong></p>
<ol type="1">
<li><p><strong>A linear model equation or</strong></p></li>
<li><p><strong>An ANOVA model equation</strong></p>
<p><span class="math display">\[
y_{ijk}=\mu+\alpha_i+\beta_j+(\alpha\beta)_{ij}+\epsilon_{ijk}
\]</span></p></li>
</ol></li>
</ol>
<p>Where mu is the overall mean, alpha_i is the fixed effect of soil type, beta_j is the fixed effect of watering frequency, alpha x beta_ij is the interaction between soil and watering, and epsilon_ijk is the residual error.</p>
</section>
</section>
<section id="section-2" class="level1">
<h1>Section 2</h1>
<section id="quantitative-and-qualitative" class="level2">
<h2 class="anchored" data-anchor-id="quantitative-and-qualitative">Quantitative and Qualitative</h2>
</section>
<section id="question-1" class="level2">
<h2 class="anchored" data-anchor-id="question-1">Question 1:</h2>
<p><strong>Part 1:</strong> Run the same model as before but with&nbsp;<code>aov</code>&nbsp;rather than&nbsp;<code>lm</code>. Compare your results with your previous model. Did the results change? Remember to look at the&nbsp;<code>summary</code>&nbsp;of your&nbsp;<code>aov</code>&nbsp;model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="do">## load the data</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>drugrat<span class="ot">&lt;-</span><span class="fu">read.csv</span>(<span class="st">"C:/Users/amber/OneDrive - University of Tennessee/Desktop/PLSC 571/Gunter HW 4 files/drug_rat.csv"</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="do">##run aov</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>model_aov<span class="ot">&lt;-</span><span class="fu">aov</span>(FC<span class="sc">~</span>IC<span class="sc">+</span>Dose, <span class="at">data=</span>drugrat)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_aov)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             Df Sum Sq Mean Sq F value Pr(&gt;F)    
IC            1  342.4   342.4  349.82 &lt;2e-16 ***
Dose          2  119.3    59.6   60.95 &lt;2e-16 ***
Residuals   146  142.9     1.0                   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="do">## run lm to compare</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>modeld<span class="ot">&lt;-</span><span class="fu">lm</span>(FC<span class="sc">~</span>IC<span class="sc">+</span>Dose,<span class="at">data=</span>drugrat)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modeld)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = FC ~ IC + Dose, data = drugrat)

Residuals:
    Min      1Q  Median      3Q     Max 
-2.2610 -0.6360  0.0000  0.6514  2.2876 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  0.51804    0.38892   1.332   0.1849    
IC           0.93384    0.05647  16.537   &lt;2e-16 ***
Dosedose1   -0.44007    0.20011  -2.199   0.0294 *  
Dosedose2   -2.09915    0.20162 -10.412   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.9893 on 146 degrees of freedom
Multiple R-squared:  0.7636,    Adjusted R-squared:  0.7588 
F-statistic: 157.2 on 3 and 146 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>The results did not change. Both models shows that initial consumption and dose had staistically significant effects (p&lt;2e-16 for both).</p>
<p><strong>Part 2:</strong> Run the same model, but with an interaction. Was the interaction significant?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="do">##  run aov with interaction</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>model_interact <span class="ot">&lt;-</span> <span class="fu">aov</span>(FC <span class="sc">~</span> IC <span class="sc">*</span> Dose, <span class="at">data =</span> drugrat)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_interact)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             Df Sum Sq Mean Sq F value Pr(&gt;F)    
IC            1  342.4   342.4 346.551 &lt;2e-16 ***
Dose          2  119.3    59.6  60.379 &lt;2e-16 ***
IC:Dose       2    0.6     0.3   0.317  0.729    
Residuals   144  142.3     1.0                   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>The interaction of IC and dose was not significant (P=0.729).</p>
<p><strong>Part 3:</strong> Run <code>TukeyHSD</code> on that last model. You should get some warning messages. Why do you think you are getting them?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="do">##tukey</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">TukeyHSD</span>(model_interact)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in replications(paste("~", xx), data = mf): non-factors ignored: IC</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in replications(paste("~", xx), data = mf): non-factors ignored: IC,
Dose</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in TukeyHSD.aov(model_interact): 'which' specified some non-factors
which will be dropped</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>  Tukey multiple comparisons of means
    95% family-wise confidence level

Fit: aov(formula = FC ~ IC * Dose, data = drugrat)

$Dose
                    diff        lwr         upr     p adj
dose1-control -0.3866032 -0.8573717  0.08416534 0.1299709
dose2-control -2.0299914 -2.5007599 -1.55922285 0.0000000
dose2-dose1   -1.6433882 -2.1141567 -1.17261965 0.0000000</code></pre>
</div>
</div>
<p>The warning is that IC is a numeric variable and TukeyHSD only works to compare factors.</p>
<p><strong>Part 4:</strong> Write the Anova equation (the additive equation) for this<br>
</p>
<p><span class="math display">\[
Y_{ij} = \mu +\alpha_i+\beta*IC_{ij}+\epsilon_ij
\]</span></p>
</section>
<section id="two-qualitative" class="level2">
<h2 class="anchored" data-anchor-id="two-qualitative">Two Qualitative</h2>
</section>
<section id="question-2" class="level2">
<h2 class="anchored" data-anchor-id="question-2">Question 2:</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="do">##load the data</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>grassdata<span class="ot">&lt;-</span><span class="fu">read.csv</span>(<span class="st">"C:/Users/amber/OneDrive - University of Tennessee/Desktop/PLSC 571/grassvarieties.csv"</span>)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(grassdata)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   90 obs. of  3 variables:
 $ Fertilizer: chr  "A" "A" "A" "A" ...
 $ Variety   : chr  "Midlawn" "Midlawn" "Midlawn" "Midlawn" ...
 $ Yield     : num  22.1 24.1 19.1 22.1 25.1 18.1 13.5 14.5 11.5 6 ...</code></pre>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(grassdata)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Fertilizer Variety Yield
1          A Midlawn  22.1
2          A Midlawn  24.1
3          A Midlawn  19.1
4          A Midlawn  22.1
5          A Midlawn  25.1
6          A Midlawn  18.1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(grassdata)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Fertilizer          Variety              Yield      
 Length:90          Length:90          Min.   : 6.00  
 Class :character   Class :character   1st Qu.:14.65  
 Mode  :character   Mode  :character   Median :18.55  
                                       Mean   :18.44  
                                       3rd Qu.:22.10  
                                       Max.   :28.60  </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="do">## change to factors</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>grassdata<span class="sc">$</span>Fertilizer <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(grassdata<span class="sc">$</span>Fertilizer)</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>grassdata<span class="sc">$</span>Variety <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(grassdata<span class="sc">$</span>Variety)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="do">##factorial ANOVA</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>model_factorial <span class="ot">&lt;-</span> <span class="fu">aov</span>(Yield <span class="sc">~</span> Fertilizer <span class="sc">*</span> Variety, <span class="at">data =</span> grassdata)</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_factorial)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                   Df Sum Sq Mean Sq F value   Pr(&gt;F)    
Fertilizer          2  953.2   476.6  24.253 7.52e-09 ***
Variety             4   11.4     2.8   0.145   0.9648    
Fertilizer:Variety  8  374.5    46.8   2.382   0.0241 *  
Residuals          75 1473.8    19.7                     
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="do">## running without an interaction to compare (question says instead of lm, but I don't remember running an lm for this in a previous assignment)</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>model_aov <span class="ot">&lt;-</span> <span class="fu">aov</span>(Yield <span class="sc">~</span> Fertilizer <span class="sc">+</span> Variety, <span class="at">data =</span> grassdata)</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_aov)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            Df Sum Sq Mean Sq F value  Pr(&gt;F)    
Fertilizer   2  953.2   476.6  21.402 3.2e-08 ***
Variety      4   11.4     2.8   0.128   0.972    
Residuals   83 1848.3    22.3                    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>I compared the model with an interaction and without, and the fertilizer was significant in each model, but in the interaction model the interaction of fertilizer and yield was also significant, so this is likely the better model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="do">##tukey</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="fu">TukeyHSD</span>(model_factorial)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Tukey multiple comparisons of means
    95% family-wise confidence level

Fit: aov(formula = Yield ~ Fertilizer * Variety, data = grassdata)

$Fertilizer
         diff        lwr       upr     p adj
B-A -7.313333 -10.050104 -4.576563 0.0000000
C-A -6.403333  -9.140104 -3.666563 0.0000010
C-B  0.910000  -1.826770  3.646770 0.7072035

$Variety
                       diff       lwr      upr     p adj
Mohawk-Midlawn  -0.32222222 -4.452537 3.808093 0.9994861
Patriot-Midlawn  0.21111111 -3.919204 4.341426 0.9999040
Riviera-Midlawn  0.57777778 -3.552537 4.708093 0.9949534
Yukon-Midlawn   -0.38888889 -4.519204 3.741426 0.9989212
Patriot-Mohawk   0.53333333 -3.596981 4.663648 0.9962956
Riviera-Mohawk   0.90000000 -3.230315 5.030315 0.9732409
Yukon-Mohawk    -0.06666667 -4.196981 4.063648 0.9999990
Riviera-Patriot  0.36666667 -3.763648 4.496981 0.9991443
Yukon-Patriot   -0.60000000 -4.730315 3.530315 0.9941651
Yukon-Riviera   -0.96666667 -5.096981 3.163648 0.9653358

$`Fertilizer:Variety`
                            diff         lwr        upr     p adj
B:Midlawn-A:Midlawn  -6.68333333 -15.6588574  2.2921907 0.3795265
C:Midlawn-A:Midlawn  -3.35000000 -12.3255241  5.6255241 0.9918893
A:Mohawk-A:Midlawn    4.20000000  -4.7755241 13.1755241 0.9434340
B:Mohawk-A:Midlawn   -8.26666667 -17.2421907  0.7088574 0.1036567
C:Mohawk-A:Midlawn   -6.93333333 -15.9088574  2.0421907 0.3200109
A:Patriot-A:Midlawn   1.36666667  -7.6088574 10.3421907 0.9999998
B:Patriot-A:Midlawn  -6.31666667 -15.2921907  2.6588574 0.4750345
C:Patriot-A:Midlawn  -4.45000000 -13.4255241  4.5255241 0.9137094
A:Riviera-A:Midlawn   0.08333333  -8.8921907  9.0588574 1.0000000
B:Riviera-A:Midlawn  -6.53333333 -15.5088574  2.4421907 0.4175920
C:Riviera-A:Midlawn  -1.85000000 -10.8255241  7.1255241 0.9999896
A:Yukon-A:Midlawn     0.56666667  -8.4088574  9.5421907 1.0000000
B:Yukon-A:Midlawn    -2.55000000 -11.5255241  6.4255241 0.9995267
C:Yukon-A:Midlawn    -9.21666667 -18.1921907 -0.2411426 0.0383369
C:Midlawn-B:Midlawn   3.33333333  -5.6421907 12.3088574 0.9922658
A:Mohawk-B:Midlawn   10.88333333   1.9078093 19.8588574 0.0049838
B:Mohawk-B:Midlawn   -1.58333333 -10.5588574  7.3921907 0.9999985
C:Mohawk-B:Midlawn   -0.25000000  -9.2255241  8.7255241 1.0000000
A:Patriot-B:Midlawn   8.05000000  -0.9255241 17.0255241 0.1273903
B:Patriot-B:Midlawn   0.36666667  -8.6088574  9.3421907 1.0000000
C:Patriot-B:Midlawn   2.23333333  -6.7421907 11.2088574 0.9998972
A:Riviera-B:Midlawn   6.76666667  -2.2088574 15.7421907 0.3591058
B:Riviera-B:Midlawn   0.15000000  -8.8255241  9.1255241 1.0000000
C:Riviera-B:Midlawn   4.83333333  -4.1421907 13.8088574 0.8511855
A:Yukon-B:Midlawn     7.25000000  -1.7255241 16.2255241 0.2528385
B:Yukon-B:Midlawn     4.13333333  -4.8421907 13.1088574 0.9499600
C:Yukon-B:Midlawn    -2.53333333 -11.5088574  6.4421907 0.9995603
A:Mohawk-C:Midlawn    7.55000000  -1.4255241 16.5255241 0.1984032
B:Mohawk-C:Midlawn   -4.91666667 -13.8921907  4.0588574 0.8349037
C:Mohawk-C:Midlawn   -3.58333333 -12.5588574  5.3921907 0.9848752
A:Patriot-C:Midlawn   4.71666667  -4.2588574 13.6921907 0.8723967
B:Patriot-C:Midlawn  -2.96666667 -11.9421907  6.0088574 0.9975768
C:Patriot-C:Midlawn  -1.10000000 -10.0755241  7.8755241 1.0000000
A:Riviera-C:Midlawn   3.43333333  -5.5421907 12.4088574 0.9897769
B:Riviera-C:Midlawn  -3.18333333 -12.1588574  5.7921907 0.9950556
C:Riviera-C:Midlawn   1.50000000  -7.4755241 10.4755241 0.9999993
A:Yukon-C:Midlawn     3.91666667  -5.0588574 12.8921907 0.9674495
B:Yukon-C:Midlawn     0.80000000  -8.1755241  9.7755241 1.0000000
C:Yukon-C:Midlawn    -5.86666667 -14.8421907  3.1088574 0.5991768
B:Mohawk-A:Mohawk   -12.46666667 -21.4421907 -3.4911426 0.0005524
C:Mohawk-A:Mohawk   -11.13333333 -20.1088574 -2.1578093 0.0035737
A:Patriot-A:Mohawk   -2.83333333 -11.8088574  6.1421907 0.9985041
B:Patriot-A:Mohawk  -10.51666667 -19.4921907 -1.5411426 0.0080250
C:Patriot-A:Mohawk   -8.65000000 -17.6255241  0.3255241 0.0705826
A:Riviera-A:Mohawk   -4.11666667 -13.0921907  4.8588574 0.9515039
B:Riviera-A:Mohawk  -10.73333333 -19.7088574 -1.7578093 0.0060664
C:Riviera-A:Mohawk   -6.05000000 -15.0255241  2.9255241 0.5482979
A:Yukon-A:Mohawk     -3.63333333 -12.6088574  5.3421907 0.9828821
B:Yukon-A:Mohawk     -6.75000000 -15.7255241  2.2255241 0.3631455
C:Yukon-A:Mohawk    -13.41666667 -22.3921907 -4.4411426 0.0001347
C:Mohawk-B:Mohawk     1.33333333  -7.6421907 10.3088574 0.9999998
A:Patriot-B:Mohawk    9.63333333   0.6578093 18.6088574 0.0237676
B:Patriot-B:Mohawk    1.95000000  -7.0255241 10.9255241 0.9999800
C:Patriot-B:Mohawk    3.81666667  -5.1588574 12.7921907 0.9737694
A:Riviera-B:Mohawk    8.35000000  -0.6255241 17.3255241 0.0955474
B:Riviera-B:Mohawk    1.73333333  -7.2421907 10.7088574 0.9999954
C:Riviera-B:Mohawk    6.41666667  -2.5588574 15.3921907 0.4482109
A:Yukon-B:Mohawk      8.83333333  -0.1421907 17.8088574 0.0582426
B:Yukon-B:Mohawk      5.71666667  -3.2588574 14.6921907 0.6404294
C:Yukon-B:Mohawk     -0.95000000  -9.9255241  8.0255241 1.0000000
A:Patriot-C:Mohawk    8.30000000  -0.6755241 17.2755241 0.1003478
B:Patriot-C:Mohawk    0.61666667  -8.3588574  9.5921907 1.0000000
C:Patriot-C:Mohawk    2.48333333  -6.4921907 11.4588574 0.9996489
A:Riviera-C:Mohawk    7.01666667  -1.9588574 15.9921907 0.3013995
B:Riviera-C:Mohawk    0.40000000  -8.5755241  9.3755241 1.0000000
C:Riviera-C:Mohawk    5.08333333  -3.8921907 14.0588574 0.7996623
A:Yukon-C:Mohawk      7.50000000  -1.4755241 16.4755241 0.2068447
B:Yukon-C:Mohawk      4.38333333  -4.5921907 13.3588574 0.9224716
C:Yukon-C:Mohawk     -2.28333333 -11.2588574  6.6921907 0.9998666
B:Patriot-A:Patriot  -7.68333333 -16.6588574  1.2921907 0.1771135
C:Patriot-A:Patriot  -5.81666667 -14.7921907  3.1588574 0.6129929
A:Riviera-A:Patriot  -1.28333333 -10.2588574  7.6921907 0.9999999
B:Riviera-A:Patriot  -7.90000000 -16.8755241  1.0755241 0.1462151
C:Riviera-A:Patriot  -3.21666667 -12.1921907  5.7588574 0.9945217
A:Yukon-A:Patriot    -0.80000000  -9.7755241  8.1755241 1.0000000
B:Yukon-A:Patriot    -3.91666667 -12.8921907  5.0588574 0.9674495
C:Yukon-A:Patriot   -10.58333333 -19.5588574 -1.6078093 0.0073669
C:Patriot-B:Patriot   1.86666667  -7.1088574 10.8421907 0.9999883
A:Riviera-B:Patriot   6.40000000  -2.5755241 15.3755241 0.4526476
B:Riviera-B:Patriot  -0.21666667  -9.1921907  8.7588574 1.0000000
C:Riviera-B:Patriot   4.46666667  -4.5088574 13.4421907 0.9114217
A:Yukon-B:Patriot     6.88333333  -2.0921907 15.8588574 0.3314836
B:Yukon-B:Patriot     3.76666667  -5.2088574 12.7421907 0.9765560
C:Yukon-B:Patriot    -2.90000000 -11.8755241  6.0755241 0.9980877
A:Riviera-C:Patriot   4.53333333  -4.4421907 13.5088574 0.9018794
B:Riviera-C:Patriot  -2.08333333 -11.0588574  6.8921907 0.9999552
C:Riviera-C:Patriot   2.60000000  -6.3755241 11.5755241 0.9994123
A:Yukon-C:Patriot     5.01666667  -3.9588574 13.9921907 0.8141727
B:Yukon-C:Patriot     1.90000000  -7.0755241 10.8755241 0.9999855
C:Yukon-C:Patriot    -4.76666667 -13.7421907  4.2088574 0.8635360
B:Riviera-A:Riviera  -6.61666667 -15.5921907  2.3588574 0.3962476
C:Riviera-A:Riviera  -1.93333333 -10.9088574  7.0421907 0.9999820
A:Yukon-A:Riviera     0.48333333  -8.4921907  9.4588574 1.0000000
B:Yukon-A:Riviera    -2.63333333 -11.6088574  6.3421907 0.9993233
C:Yukon-A:Riviera    -9.30000000 -18.2755241 -0.3244759 0.0349072
C:Riviera-B:Riviera   4.68333333  -4.2921907 13.6588574 0.8781099
A:Yukon-B:Riviera     7.10000000  -1.8755241 16.0755241 0.2834452
B:Yukon-B:Riviera     3.98333333  -4.9921907 12.9588574 0.9626457
C:Yukon-B:Riviera    -2.68333333 -11.6588574  6.2921907 0.9991679
A:Yukon-C:Riviera     2.41666667  -6.5588574 11.3921907 0.9997425
B:Yukon-C:Riviera    -0.70000000  -9.6755241  8.2755241 1.0000000
C:Yukon-C:Riviera    -7.36666667 -16.3421907  1.6088574 0.2305887
B:Yukon-A:Yukon      -3.11666667 -12.0921907  5.8588574 0.9959947
C:Yukon-A:Yukon      -9.78333333 -18.7588574 -0.8078093 0.0198975
C:Yukon-B:Yukon      -6.66666667 -15.6421907  2.3088574 0.3836758</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="do">## extra credit attempt at contrast analysis</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(multcomp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'multcomp' was built under R version 4.4.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: mvtnorm</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'mvtnorm' was built under R version 4.4.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: survival</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: TH.data</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'TH.data' was built under R version 4.4.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: MASS</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'TH.data'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:MASS':

    geyser</code></pre>
</div>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="do">##combine factor</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>grassdata<span class="sc">$</span>Group <span class="ot">&lt;-</span> <span class="fu">interaction</span>(grassdata<span class="sc">$</span>Fertilizer, grassdata<span class="sc">$</span>Variety)</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a><span class="do">##model</span></span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>model_contrast <span class="ot">&lt;-</span> <span class="fu">aov</span>(Yield <span class="sc">~</span> Group, <span class="at">data =</span> grassdata)</span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a><span class="do">##contrast 1 Fertilizer A in Midlawn vs A in Mohawk</span></span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a>contrast1 <span class="ot">&lt;-</span> <span class="fu">glht</span>(model_contrast, <span class="at">linfct =</span> <span class="fu">mcp</span>(<span class="at">Group =</span> <span class="fu">c</span>(<span class="st">"A.Midlawn - A.Mohawk = 0"</span>)))</span>
<span id="cb35-9"><a href="#cb35-9" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(contrast1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
     Simultaneous Tests for General Linear Hypotheses

Multiple Comparisons of Means: User-defined Contrasts


Fit: aov(formula = Yield ~ Group, data = grassdata)

Linear Hypotheses:
                          Estimate Std. Error t value Pr(&gt;|t|)
A.Midlawn - A.Mohawk == 0   -4.200      2.559  -1.641    0.105
(Adjusted p values reported -- single-step method)</code></pre>
</div>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="do">##contrast 2 Variety B in Yukon and Rivera Vs B in Midlawn and Mohawk</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>contrast2 <span class="ot">&lt;-</span> <span class="fu">glht</span>(model_contrast, <span class="at">linfct =</span> <span class="fu">mcp</span>(<span class="at">Group =</span> <span class="fu">c</span>(</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>  <span class="st">"(B.Yukon + B.Riviera)/2 - (B.Midlawn + B.Mohawk)/2 = 0"</span></span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>)))</span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(contrast2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
     Simultaneous Tests for General Linear Hypotheses

Multiple Comparisons of Means: User-defined Contrasts


Fit: aov(formula = Yield ~ Group, data = grassdata)

Linear Hypotheses:
                                                        Estimate Std. Error
(B.Yukon + B.Riviera)/2 - (B.Midlawn + B.Mohawk)/2 == 0    2.933      1.810
                                                        t value Pr(&gt;|t|)
(B.Yukon + B.Riviera)/2 - (B.Midlawn + B.Mohawk)/2 == 0   1.621    0.109
(Adjusted p values reported -- single-step method)</code></pre>
</div>
</div>
</section>
<section id="randomized-complete-block-design" class="level2">
<h2 class="anchored" data-anchor-id="randomized-complete-block-design">Randomized Complete Block Design</h2>
</section>
<section id="question-3" class="level2">
<h2 class="anchored" data-anchor-id="question-3">Question 3:</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="do">##load data</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>mdat<span class="ot">&lt;-</span><span class="fu">read.csv</span>(<span class="st">"C:/Users/amber/OneDrive - University of Tennessee/Desktop/PLSC 571/mdat.csv"</span>)</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(mdat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   12 obs. of  3 variables:
 $ Region   : int  1 1 1 2 2 2 3 3 3 4 ...
 $ Treatment: chr  "Control" "Bt" "Dimilin" "Control" ...
 $ Larvae   : int  25 16 14 10 3 2 15 10 16 32 ...</code></pre>
</div>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(mdat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Region Treatment Larvae
1      1   Control     25
2      1        Bt     16
3      1   Dimilin     14
4      2   Control     10
5      2        Bt      3
6      2   Dimilin      2</code></pre>
</div>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mdat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     Region      Treatment             Larvae     
 Min.   :1.00   Length:12          Min.   : 2.00  
 1st Qu.:1.75   Class :character   1st Qu.:10.00  
 Median :2.50   Mode  :character   Median :14.50  
 Mean   :2.50                      Mean   :14.42  
 3rd Qu.:3.25                      3rd Qu.:16.50  
 Max.   :4.00                      Max.   :32.00  </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="do">## change to factors</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>mdat<span class="sc">$</span>Region <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(mdat<span class="sc">$</span>Region)</span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>mdat<span class="sc">$</span>Treatment <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(mdat<span class="sc">$</span>Treatment)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Part 1:</strong> Run an anova using <code>aov</code> . <strong>ONLY</strong> test the effects of treatment (ignore the potential regional effect). Look at the summary ans interpret..</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="do">##run anova only on effects of treatment</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>model_aov<span class="ot">&lt;-</span><span class="fu">aov</span>(Larvae<span class="sc">~</span>Treatment, <span class="at">data=</span>mdat)</span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_aov)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            Df Sum Sq Mean Sq F value Pr(&gt;F)
Treatment    2  223.2  111.58    1.84  0.214
Residuals    9  545.8   60.64               </code></pre>
</div>
</div>
<p>The effect of treatment on number of larvae is not significant.</p>
<p><strong>Part 2:</strong> Run the same model, but add the effect of region (as a fixed effect). What changed? Why? Interpret the results.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="do">##model with effect of region</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>model_region <span class="ot">&lt;-</span> <span class="fu">aov</span>(Larvae <span class="sc">~</span> Region <span class="sc">+</span> Treatment, <span class="at">data =</span> mdat)</span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_region)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            Df Sum Sq Mean Sq F value Pr(&gt;F)  
Region       3  430.9  143.64   7.505 0.0187 *
Treatment    2  223.2  111.58   5.830 0.0392 *
Residuals    6  114.8   19.14                 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Both region and treatment had significant effects on number of larvae. When I ran the model before without region, there was more unexplained variation so the treatment effect wasn’t clear. When I added region, it reduced unexplained variation and made treatment effect visible.</p>
<p><strong>Part 3:</strong> Now, let’s run the same model with region as a random effect. In this case, we do it using the following equation:<br>
<br>
Do you see any differences with including he blocking factor as random or fixed? Why?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="do">##run same model with region as a random effect</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>av1<span class="ot">&lt;-</span><span class="fu">aov</span>(Larvae<span class="sc">~</span>Treatment<span class="sc">+</span><span class="fu">Error</span>(Region),<span class="at">data=</span>mdat)</span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(av1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Error: Region
          Df Sum Sq Mean Sq F value Pr(&gt;F)
Residuals  3  430.9   143.6               

Error: Within
          Df Sum Sq Mean Sq F value Pr(&gt;F)  
Treatment  2  223.2  111.58    5.83 0.0392 *
Residuals  6  114.8   19.14                 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>The treatment effect remained significant, and the p value still = 0.0392 in both cases. However there is no F value or p value when we include it as a random effect, because its just being treated as background variation and not of primary interest.</p>
</section>
<section id="nested-design" class="level2">
<h2 class="anchored" data-anchor-id="nested-design">Nested Design</h2>
</section>
<section id="question-4" class="level2">
<h2 class="anchored" data-anchor-id="question-4">Question 4:</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="do">## load data</span></span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>mdat2<span class="ot">&lt;-</span><span class="fu">read.csv</span>(<span class="st">"C:/Users/amber/OneDrive - University of Tennessee/Desktop/PLSC 571/mdat2.csv"</span>)</span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(mdat2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   36 obs. of  3 variables:
 $ larvae   : num  16 16 15.8 14.2 13.9 14.2 13.5 13.4 14 13.1 ...
 $ Treatment: chr  "Bt" "Bt" "Bt" "Bt" ...
 $ Plot     : int  1 1 1 1 2 2 2 2 3 3 ...</code></pre>
</div>
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(mdat2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  larvae Treatment Plot
1   16.0        Bt    1
2   16.0        Bt    1
3   15.8        Bt    1
4   14.2        Bt    1
5   13.9        Bt    2
6   14.2        Bt    2</code></pre>
</div>
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mdat2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     larvae       Treatment              Plot  
 Min.   :12.00   Length:36          Min.   :1  
 1st Qu.:13.32   Class :character   1st Qu.:3  
 Median :14.10   Mode  :character   Median :5  
 Mean   :15.39                      Mean   :5  
 3rd Qu.:18.18                      3rd Qu.:7  
 Max.   :20.90                      Max.   :9  </code></pre>
</div>
</div>
<p><strong>Part 1:</strong> Run an anova using <code>aov</code> . <strong>ONLY</strong> test the effects of treatment. Look at the results using <code>summary</code>. Explain why this is the wrong approach to analyzing this data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="do">##convert to factor</span></span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a>mdat2<span class="sc">$</span>Treatment <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(mdat2<span class="sc">$</span>Treatment)</span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-4"><a href="#cb58-4" aria-hidden="true" tabindex="-1"></a><span class="do">##run anova</span></span>
<span id="cb58-5"><a href="#cb58-5" aria-hidden="true" tabindex="-1"></a>model_wrong <span class="ot">&lt;-</span> <span class="fu">aov</span>(larvae <span class="sc">~</span> Treatment, <span class="at">data =</span> mdat2)</span>
<span id="cb58-6"><a href="#cb58-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_wrong)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            Df Sum Sq Mean Sq F value Pr(&gt;F)    
Treatment    2 215.39  107.69   141.7 &lt;2e-16 ***
Residuals   33  25.09    0.76                   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>This is the wrong approach because this treats all of the observations like they are independent, but they are nested with the plots so its pseudoreplication.</p>
<p><strong>Part 2:</strong> Run the same model, but add the effect of plot (as a fixed effect). This is also the incorrect approach, as we want plot to be a random effect.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="do">## convert plot to factor</span></span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a>mdat2<span class="sc">$</span>Plot <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(mdat2<span class="sc">$</span>Plot)</span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-4"><a href="#cb60-4" aria-hidden="true" tabindex="-1"></a><span class="do">##run with plot as fixed effect</span></span>
<span id="cb60-5"><a href="#cb60-5" aria-hidden="true" tabindex="-1"></a>model_fixed_plot <span class="ot">&lt;-</span> <span class="fu">aov</span>(larvae <span class="sc">~</span> Plot <span class="sc">+</span> Treatment, <span class="at">data =</span> mdat2)</span>
<span id="cb60-6"><a href="#cb60-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_fixed_plot)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            Df Sum Sq Mean Sq F value   Pr(&gt;F)    
Plot         8 226.56  28.319   54.93 1.03e-14 ***
Residuals   27  13.92   0.516                     
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p><strong>Part 3:</strong> Run the same model, with plot as a random effect <code>Error(Plot)</code>. This is the correct model. Explain why, and look at the <code>summary</code> and describe the results.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a>model_correct <span class="ot">&lt;-</span> <span class="fu">aov</span>(larvae <span class="sc">~</span> Treatment <span class="sc">+</span> <span class="fu">Error</span>(Plot), <span class="at">data =</span> mdat2)</span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_correct)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Error: Plot
          Df Sum Sq Mean Sq F value  Pr(&gt;F)    
Treatment  2 215.39  107.69   57.87 0.00012 ***
Residuals  6  11.17    1.86                    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Error: Within
          Df Sum Sq Mean Sq F value Pr(&gt;F)
Residuals 27  13.92  0.5156               </code></pre>
</div>
</div>
<p>This is the correct model because treatment was applied at the plot level and each plot was independent but it is not of interest in the study. So this accounts for the variance, but without considering it as a fixed effect/of interest in the study. Using this model, the treatment had a highly significant effect of larvae (p=0.00012). When I added plot+treatment as fixed effects, they were completely confounded and only returned results for plot.</p>
<p><strong>Part 4:</strong> Write the additive (ANOVA) equation for the correct model and describe it</p>
<p><span class="math display">\[
Y_{ij}=\mu+\alpha_i+\gamma_j+\epsilon_{ij}
\]</span></p>
<p>Where Y_ij is the larvae count from the jth subsample in the ith treatment group, mu is the overall mean larvae abundance, alpha_i is the fixed effect of treatment, gamma_ij s the random effect of plot and epsilon_ij is the residual error (variation among subsamples with the plot)</p>
</section>
<section id="split-plot-design" class="level2">
<h2 class="anchored" data-anchor-id="split-plot-design">Split Plot Design</h2>
</section>
<section id="question-5" class="level2">
<h2 class="anchored" data-anchor-id="question-5">Question 5:</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="do">## load the data</span></span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a>coffee<span class="ot">&lt;-</span><span class="fu">read.csv</span>(<span class="st">"C:/Users/amber/OneDrive - University of Tennessee/Desktop/PLSC 571/coffee.csv"</span>)</span>
<span id="cb64-3"><a href="#cb64-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-4"><a href="#cb64-4" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(coffee)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   64 obs. of  5 variables:
 $ plot      : int  1 2 3 4 1 2 3 4 1 2 ...
 $ cover_crop: chr  "Control" "Control" "Control" "Control" ...
 $ fertilizer: chr  "Control" "Control" "Control" "Control" ...
 $ y         : num  14.27 14.89 12.83 7.19 11.53 ...
 $ WU        : int  2 6 10 14 1 5 9 13 3 7 ...</code></pre>
</div>
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(coffee)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  plot cover_crop fertilizer         y WU
1    1    Control    Control 14.271038  2
2    2    Control    Control 14.893341  6
3    3    Control    Control 12.828227 10
4    4    Control    Control  7.187256 14
5    1    Cajanus    Control 11.525040  1
6    2    Cajanus    Control  6.962143  5</code></pre>
</div>
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(coffee)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      plot       cover_crop         fertilizer              y         
 Min.   :1.00   Length:64          Length:64          Min.   : 3.055  
 1st Qu.:1.75   Class :character   Class :character   1st Qu.: 6.958  
 Median :2.50   Mode  :character   Mode  :character   Median :10.990  
 Mean   :2.50                                         Mean   :11.153  
 3rd Qu.:3.25                                         3rd Qu.:14.298  
 Max.   :4.00                                         Max.   :23.651  
       WU       
 Min.   : 1.00  
 1st Qu.: 4.75  
 Median : 8.50  
 Mean   : 8.50  
 3rd Qu.:12.25  
 Max.   :16.00  </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="do">##convert to factors</span></span>
<span id="cb70-2"><a href="#cb70-2" aria-hidden="true" tabindex="-1"></a>coffee<span class="sc">$</span>plot<span class="ot">&lt;-</span><span class="fu">factor</span>(coffee<span class="sc">$</span>plot)</span>
<span id="cb70-3"><a href="#cb70-3" aria-hidden="true" tabindex="-1"></a>coffee<span class="sc">$</span>WU<span class="ot">&lt;-</span><span class="fu">factor</span>(coffee<span class="sc">$</span>WU)</span>
<span id="cb70-4"><a href="#cb70-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb70-5"><a href="#cb70-5" aria-hidden="true" tabindex="-1"></a><span class="do">##run ANOVA</span></span>
<span id="cb70-6"><a href="#cb70-6" aria-hidden="true" tabindex="-1"></a>coffeeaov<span class="ot">&lt;-</span><span class="fu">aov</span>(y<span class="sc">~</span>cover_crop<span class="sc">+</span>fertilizer<span class="sc">+</span>cover_crop<span class="sc">:</span>fertilizer<span class="sc">+</span>plot<span class="sc">+</span><span class="fu">Error</span>(WU), <span class="at">data=</span>coffee)</span>
<span id="cb70-7"><a href="#cb70-7" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(coffeeaov)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Error: WU
           Df Sum Sq Mean Sq F value   Pr(&gt;F)    
cover_crop  3  379.0  126.34   51.92 5.26e-06 ***
plot        3  215.3   71.77   29.49 5.49e-05 ***
Residuals   9   21.9    2.43                     
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Error: Within
                      Df Sum Sq Mean Sq F value   Pr(&gt;F)    
fertilizer             3  663.4  221.14  73.640 1.97e-15 ***
cover_crop:fertilizer  9  151.0   16.78   5.587 8.12e-05 ***
Residuals             36  108.1    3.00                     
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p><strong>Part 1:</strong> Explore the data and describe it</p>
<p>The plot is an integer (that we changed to factor) and this is the subplot within each whole unit (4 plots per WU) and used as a fixed blocking factor in WU.</p>
<p>cover_crop is the whole unit treatment or type of cover crop used and is randomized across all 16 WUs.</p>
<p>fertilizer is the subplot treatment that was applied within each WU.</p>
<p>y is the response variable (i assume for yield?)</p>
<p>WU is the whole unit identifier.</p>
<p><strong>Part 2:</strong> Explore the summary of the model and describe it.</p>
<p>The summary shows that among WU, cover crop and plot had significant effects on yield (both p-values &lt;0.05). And within WU, both the fertilizer and the interaction of the fertilizer and cover crops were significant. So this would suggest that the effect of the fertilizer depended on which cover crop was used.<br>
<br>
<strong>Part 3</strong>: Write the equation (anova)</p>
<p><span class="math display">\[
Y_{ijkl}=\mu+\alpha_i+\beta_j+(\alpha\beta)_{ij} + \gamma_k + \delta_{ik} +\epsilon_{ijkl}
\]</span></p>
<p><strong>Part 4:</strong> &nbsp;Check whether we estimated the degrees of freedom correctly on the slideshow<br>
</p>
<p>Yes, the degrees of freedom from the slideshow match those from the models. Cover crop 3, plit 3, residual 9 among WU, and fertilizer 3, interaction 9, and residuals 36 at the within-level. These total 63, which checks out with n-1 if we have 64 total observations.<br>
<br>
<strong>Part 5:</strong> Why is plot random?</p>
<p>Plot is random because it represents the subplots within each whole unit, but we aren’t interested in comparing the plots. We don’t care about the difference between plot 1, 2, 3 or 4. But we modeled it as a fixed effect, I assume because aov can only handle one random effect at a time and we treated WU as a random efect.</p>
<p><strong>Extra credit:</strong> Plot the results and describe them.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="do">##plot it</span></span>
<span id="cb72-2"><a href="#cb72-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb72-3"><a href="#cb72-3" aria-hidden="true" tabindex="-1"></a>coffee<span class="sc">$</span>treatment_group <span class="ot">&lt;-</span> <span class="fu">interaction</span>(coffee<span class="sc">$</span>cover_crop, coffee<span class="sc">$</span>fertilizer)</span>
<span id="cb72-4"><a href="#cb72-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-5"><a href="#cb72-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(coffee, <span class="fu">aes</span>(<span class="at">x =</span> treatment_group, <span class="at">y =</span> y)) <span class="sc">+</span></span>
<span id="cb72-6"><a href="#cb72-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun =</span> mean, <span class="at">geom =</span> <span class="st">"point"</span>, <span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb72-7"><a href="#cb72-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun.data =</span> mean_se, <span class="at">geom =</span> <span class="st">"errorbar"</span>, <span class="at">width =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb72-8"><a href="#cb72-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb72-9"><a href="#cb72-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Cover Crop × Fertilizer"</span>, <span class="at">y =</span> <span class="st">"Response (y)"</span>,</span>
<span id="cb72-10"><a href="#cb72-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Mean Response by Treatment Combination"</span>) <span class="sc">+</span></span>
<span id="cb72-11"><a href="#cb72-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>, <span class="at">hjust =</span> <span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Assignment-Design_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="do">## plot with facet by cover crop</span></span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(coffee, <span class="fu">aes</span>(<span class="at">x =</span> fertilizer, <span class="at">y =</span> y)) <span class="sc">+</span></span>
<span id="cb73-3"><a href="#cb73-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun =</span> mean, <span class="at">geom =</span> <span class="st">"point"</span>, <span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb73-4"><a href="#cb73-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun.data =</span> mean_se, <span class="at">geom =</span> <span class="st">"errorbar"</span>, <span class="at">width =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb73-5"><a href="#cb73-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> cover_crop) <span class="sc">+</span></span>
<span id="cb73-6"><a href="#cb73-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb73-7"><a href="#cb73-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Fertilizer"</span>, <span class="at">y =</span> <span class="st">"Response (y)"</span>, <span class="at">title =</span> <span class="st">"Response by Fertilizer within Cover Crops"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Assignment-Design_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The plots show the mean y for each combination of cover crop and fertilzier with error bars for the standard error.</p>
<p>It appears that Raphanus combined with Fungi has the highest response followed by Control and Fungi.</p>
<p>Cajanus was generally lower across all fertilizer treatments.</p>
<p>This shows that effectiveness of a fertilizer depends on cover crop because Fungi for example, was very effective with Raphanus, but not as much with Cajanus. But Raphanus was not as effective with the control.</p>
</section>
<section id="linear-model-lme" class="level2">
<h2 class="anchored" data-anchor-id="linear-model-lme">Linear Model (lme)</h2>
</section>
<section id="question-6" class="level2">
<h2 class="anchored" data-anchor-id="question-6">Question 6:</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="do">##load package</span></span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(nlme)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'nlme' was built under R version 4.4.3</code></pre>
</div>
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a>lme.coffee <span class="ot">&lt;-</span> <span class="fu">lme</span>(y <span class="sc">~</span> fertilizer<span class="sc">*</span>cover_crop,</span>
<span id="cb76-2"><a href="#cb76-2" aria-hidden="true" tabindex="-1"></a>                <span class="at">data =</span> coffee,</span>
<span id="cb76-3"><a href="#cb76-3" aria-hidden="true" tabindex="-1"></a>                <span class="at">correlation =</span> <span class="fu">corCompSymm</span>(), <span class="co"># To make results same as aov()</span></span>
<span id="cb76-4"><a href="#cb76-4" aria-hidden="true" tabindex="-1"></a>                <span class="at">random =</span> <span class="sc">~</span><span class="dv">1</span><span class="sc">|</span>plot<span class="sc">/</span>WU)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Part 1:</strong> &nbsp;Run a summary on the linear model, also run an anova using <code>anova(lme.coffee</code>) and interpret the results.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="do">##run a summary</span></span>
<span id="cb77-2"><a href="#cb77-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lme.coffee)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Linear mixed-effects model fit by REML
  Data: coffee 
       AIC      BIC    logLik
  258.8078 296.2318 -109.4039

Random effects:
 Formula: ~1 | plot
        (Intercept)
StdDev:     2.08167

 Formula: ~1 | WU %in% plot
        (Intercept) Residual
StdDev:   0.3395035 1.656889

Correlation Structure: Compound symmetry
 Formula: ~1 | plot/WU 
 Parameter estimate(s):
        Rho 
-0.09385947 
Fixed effects:  y ~ fertilizer * cover_crop 
                                           Value Std.Error DF   t-value p-value
(Intercept)                             5.028560  1.341072 36  3.749658  0.0006
fertilizerCoffee                        0.263720  1.225347 36  0.215221  0.8308
fertilizerControl                       1.821612  1.225347 36  1.486609  0.1458
fertilizerFungi                         6.175642  1.225347 36  5.039913  0.0000
cover_cropControl                       2.523470  1.195940  9  2.110031  0.0641
cover_cropCrotalaria                    5.453199  1.195940  9  4.559761  0.0014
cover_cropRaphanus                      3.574589  1.195940  9  2.988937  0.0152
fertilizerCoffee:cover_cropControl      0.041316  1.732903 36  0.023842  0.9811
fertilizerControl:cover_cropControl     2.921323  1.732903 36  1.685798  0.1005
fertilizerFungi:cover_cropControl       4.767603  1.732903 36  2.751224  0.0092
fertilizerCoffee:cover_cropCrotalaria  -2.278675  1.732903 36 -1.314947  0.1968
fertilizerControl:cover_cropCrotalaria  4.002853  1.732903 36  2.309912  0.0267
fertilizerFungi:cover_cropCrotalaria   -1.626723  1.732903 36 -0.938727  0.3541
fertilizerCoffee:cover_cropRaphanus     3.995689  1.732903 36  2.305778  0.0270
fertilizerControl:cover_cropRaphanus    2.321071  1.732903 36  1.339413  0.1888
fertilizerFungi:cover_cropRaphanus      4.603457  1.732903 36  2.656501  0.0117
 Correlation: 
                                       (Intr) frtlzrCf frtlzrCn frtlzF
fertilizerCoffee                       -0.457                         
fertilizerControl                      -0.457  0.500                  
fertilizerFungi                        -0.457  0.500    0.500         
cover_cropControl                      -0.446  0.512    0.512    0.512
cover_cropCrotalaria                   -0.446  0.512    0.512    0.512
cover_cropRaphanus                     -0.446  0.512    0.512    0.512
fertilizerCoffee:cover_cropControl      0.323 -0.707   -0.354   -0.354
fertilizerControl:cover_cropControl     0.323 -0.354   -0.707   -0.354
fertilizerFungi:cover_cropControl       0.323 -0.354   -0.354   -0.707
fertilizerCoffee:cover_cropCrotalaria   0.323 -0.707   -0.354   -0.354
fertilizerControl:cover_cropCrotalaria  0.323 -0.354   -0.707   -0.354
fertilizerFungi:cover_cropCrotalaria    0.323 -0.354   -0.354   -0.707
fertilizerCoffee:cover_cropRaphanus     0.323 -0.707   -0.354   -0.354
fertilizerControl:cover_cropRaphanus    0.323 -0.354   -0.707   -0.354
fertilizerFungi:cover_cropRaphanus      0.323 -0.354   -0.354   -0.707
                                       cvr_crpCn cvr_crpCr cvr_cR
fertilizerCoffee                                                 
fertilizerControl                                                
fertilizerFungi                                                  
cover_cropControl                                                
cover_cropCrotalaria                    0.500                    
cover_cropRaphanus                      0.500     0.500          
fertilizerCoffee:cover_cropControl     -0.724    -0.362    -0.362
fertilizerControl:cover_cropControl    -0.724    -0.362    -0.362
fertilizerFungi:cover_cropControl      -0.724    -0.362    -0.362
fertilizerCoffee:cover_cropCrotalaria  -0.362    -0.724    -0.362
fertilizerControl:cover_cropCrotalaria -0.362    -0.724    -0.362
fertilizerFungi:cover_cropCrotalaria   -0.362    -0.724    -0.362
fertilizerCoffee:cover_cropRaphanus    -0.362    -0.362    -0.724
fertilizerControl:cover_cropRaphanus   -0.362    -0.362    -0.724
fertilizerFungi:cover_cropRaphanus     -0.362    -0.362    -0.724
                                       frtlzrCff:cvr_crpCn
fertilizerCoffee                                          
fertilizerControl                                         
fertilizerFungi                                           
cover_cropControl                                         
cover_cropCrotalaria                                      
cover_cropRaphanus                                        
fertilizerCoffee:cover_cropControl                        
fertilizerControl:cover_cropControl     0.500             
fertilizerFungi:cover_cropControl       0.500             
fertilizerCoffee:cover_cropCrotalaria   0.500             
fertilizerControl:cover_cropCrotalaria  0.250             
fertilizerFungi:cover_cropCrotalaria    0.250             
fertilizerCoffee:cover_cropRaphanus     0.500             
fertilizerControl:cover_cropRaphanus    0.250             
fertilizerFungi:cover_cropRaphanus      0.250             
                                       frtlzrCntrl:cvr_crpCn
fertilizerCoffee                                            
fertilizerControl                                           
fertilizerFungi                                             
cover_cropControl                                           
cover_cropCrotalaria                                        
cover_cropRaphanus                                          
fertilizerCoffee:cover_cropControl                          
fertilizerControl:cover_cropControl                         
fertilizerFungi:cover_cropControl       0.500               
fertilizerCoffee:cover_cropCrotalaria   0.250               
fertilizerControl:cover_cropCrotalaria  0.500               
fertilizerFungi:cover_cropCrotalaria    0.250               
fertilizerCoffee:cover_cropRaphanus     0.250               
fertilizerControl:cover_cropRaphanus    0.500               
fertilizerFungi:cover_cropRaphanus      0.250               
                                       frtlzrFng:cvr_crpCn frtlzrCff:cvr_crpCr
fertilizerCoffee                                                              
fertilizerControl                                                             
fertilizerFungi                                                               
cover_cropControl                                                             
cover_cropCrotalaria                                                          
cover_cropRaphanus                                                            
fertilizerCoffee:cover_cropControl                                            
fertilizerControl:cover_cropControl                                           
fertilizerFungi:cover_cropControl                                             
fertilizerCoffee:cover_cropCrotalaria   0.250                                 
fertilizerControl:cover_cropCrotalaria  0.250               0.500             
fertilizerFungi:cover_cropCrotalaria    0.500               0.500             
fertilizerCoffee:cover_cropRaphanus     0.250               0.500             
fertilizerControl:cover_cropRaphanus    0.250               0.250             
fertilizerFungi:cover_cropRaphanus      0.500               0.250             
                                       frtlzrCntrl:cvr_crpCr
fertilizerCoffee                                            
fertilizerControl                                           
fertilizerFungi                                             
cover_cropControl                                           
cover_cropCrotalaria                                        
cover_cropRaphanus                                          
fertilizerCoffee:cover_cropControl                          
fertilizerControl:cover_cropControl                         
fertilizerFungi:cover_cropControl                           
fertilizerCoffee:cover_cropCrotalaria                       
fertilizerControl:cover_cropCrotalaria                      
fertilizerFungi:cover_cropCrotalaria    0.500               
fertilizerCoffee:cover_cropRaphanus     0.250               
fertilizerControl:cover_cropRaphanus    0.500               
fertilizerFungi:cover_cropRaphanus      0.250               
                                       frtlzrFng:cvr_crpCr frtlzrCf:_R
fertilizerCoffee                                                      
fertilizerControl                                                     
fertilizerFungi                                                       
cover_cropControl                                                     
cover_cropCrotalaria                                                  
cover_cropRaphanus                                                    
fertilizerCoffee:cover_cropControl                                    
fertilizerControl:cover_cropControl                                   
fertilizerFungi:cover_cropControl                                     
fertilizerCoffee:cover_cropCrotalaria                                 
fertilizerControl:cover_cropCrotalaria                                
fertilizerFungi:cover_cropCrotalaria                                  
fertilizerCoffee:cover_cropRaphanus     0.250                         
fertilizerControl:cover_cropRaphanus    0.250               0.500     
fertilizerFungi:cover_cropRaphanus      0.500               0.500     
                                       frtlzrCn:_R
fertilizerCoffee                                  
fertilizerControl                                 
fertilizerFungi                                   
cover_cropControl                                 
cover_cropCrotalaria                              
cover_cropRaphanus                                
fertilizerCoffee:cover_cropControl                
fertilizerControl:cover_cropControl               
fertilizerFungi:cover_cropControl                 
fertilizerCoffee:cover_cropCrotalaria             
fertilizerControl:cover_cropCrotalaria            
fertilizerFungi:cover_cropCrotalaria              
fertilizerCoffee:cover_cropRaphanus               
fertilizerControl:cover_cropRaphanus              
fertilizerFungi:cover_cropRaphanus      0.500     

Standardized Within-Group Residuals:
        Min          Q1         Med          Q3         Max 
-1.89288099 -0.63403030 -0.06726563  0.53283294  1.80802622 

Number of Observations: 64
Number of Groups: 
        plot WU %in% plot 
           4           16 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lme.coffee)<span class="sc">$</span>tTable</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                             Value Std.Error DF     t-value
(Intercept)                             5.02856037  1.341072 36  3.74965768
fertilizerCoffee                        0.26371998  1.225347 36  0.21522063
fertilizerControl                       1.82161164  1.225347 36  1.48660862
fertilizerFungi                         6.17564246  1.225347 36  5.03991251
cover_cropControl                       2.52347028  1.195940  9  2.11003145
cover_cropCrotalaria                    5.45319862  1.195940  9  4.55976069
cover_cropRaphanus                      3.57458871  1.195940  9  2.98893736
fertilizerCoffee:cover_cropControl      0.04131602  1.732903 36  0.02384209
fertilizerControl:cover_cropControl     2.92132326  1.732903 36  1.68579776
fertilizerFungi:cover_cropControl       4.76760251  1.732903 36  2.75122364
fertilizerCoffee:cover_cropCrotalaria  -2.27867463  1.732903 36 -1.31494677
fertilizerControl:cover_cropCrotalaria  4.00285264  1.732903 36  2.30991212
fertilizerFungi:cover_cropCrotalaria   -1.62672290  1.732903 36 -0.93872728
fertilizerCoffee:cover_cropRaphanus     3.99568932  1.732903 36  2.30577841
fertilizerControl:cover_cropRaphanus    2.32107138  1.732903 36  1.33941252
fertilizerFungi:cover_cropRaphanus      4.60345666  1.732903 36  2.65650057
                                            p-value
(Intercept)                            6.216169e-04
fertilizerCoffee                       8.308100e-01
fertilizerControl                      1.458246e-01
fertilizerFungi                        1.329811e-05
cover_cropControl                      6.406650e-02
cover_cropCrotalaria                   1.366735e-03
cover_cropRaphanus                     1.522715e-02
fertilizerCoffee:cover_cropControl     9.811102e-01
fertilizerControl:cover_cropControl    1.004848e-01
fertilizerFungi:cover_cropControl      9.235378e-03
fertilizerCoffee:cover_cropCrotalaria  1.968429e-01
fertilizerControl:cover_cropCrotalaria 2.673805e-02
fertilizerFungi:cover_cropCrotalaria   3.541267e-01
fertilizerCoffee:cover_cropRaphanus    2.699315e-02
fertilizerControl:cover_cropRaphanus   1.888317e-01
fertilizerFungi:cover_cropRaphanus     1.169409e-02</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a><span class="do">##run anova</span></span>
<span id="cb81-2"><a href="#cb81-2" aria-hidden="true" tabindex="-1"></a>lme_anova<span class="ot">&lt;-</span><span class="fu">anova</span>(lme.coffee)</span>
<span id="cb81-3"><a href="#cb81-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lme_anova)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     numDF         denDF          F-value           p-value         
 Min.   :1.0   Min.   : 9.00   Min.   :  5.587   Min.   :0.000e+00  
 1st Qu.:2.5   1st Qu.:29.25   1st Qu.: 40.337   1st Qu.:0.000e+00  
 Median :3.0   Median :36.00   Median : 62.780   Median :2.631e-06  
 Mean   :4.0   Mean   :29.25   Mean   : 60.521   Mean   :2.162e-05  
 3rd Qu.:4.5   3rd Qu.:36.00   3rd Qu.: 82.964   3rd Qu.:2.425e-05  
 Max.   :9.0   Max.   :36.00   Max.   :110.935   Max.   :8.120e-05  </code></pre>
</div>
</div>
<p>Summary of the linear mixed effects model: Fungi fertilizer had a significant positive effect, and cover crops Crotalaria and Raphanus improved y compared to control. There were significant interaction effects. Fungi was effective with Raphanus and no cover crop. I would say that bother fertilizer and cover crop and their interactions influence the response.</p>
<p>Summary of anova: all the range of p values was statistically significant, so both the main effects and the interactions contribute to variation in response.</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>