product_type = 'connect_cloud'
'$schema' = 'https://cdn.posit.co/publisher/schemas/posit-publishing-schema-v3.json'
type = 'html'
entrypoint = 'fish-lw-assignment.html'
source = 'fish-lw-assignment.qmd'
validate = true
files = [
  '/fish-lw-assignment.html',
  '/fish-lw-assignment_files',
  '/fish-lw-assignment_files\libs\quarto-html\tippy.css',
  '/fish-lw-assignment_files\libs\quarto-html\tippy.umd.min.js',
  '/fish-lw-assignment_files\figure-html\unnamed-chunk-6-1.png',
  '/fish-lw-assignment_files\libs\quarto-html\quarto-syntax-highlighting-29e2c20b02301cfff04dc8050bf30c7e.css',
  '/fish-lw-assignment_files\libs\bootstrap\bootstrap-icons.css',
  '/fish-lw-assignment_files\libs\bootstrap\bootstrap-933a14f46f0e4d1503cecf416b5e09b4.min.css',
  '/fish-lw-assignment_files\libs\quarto-html\quarto.js',
  '/fish-lw-assignment_files\libs\bootstrap\bootstrap.min.js',
  '/fish-lw-assignment_files\figure-html\unnamed-chunk-1-1.png',
  '/fish-lw-assignment_files\libs\clipboard\clipboard.min.js',
  '/fish-lw-assignment_files\libs\quarto-html\popper.min.js',
  '/fish-lw-assignment_files\libs\quarto-html\anchor.min.js',
  '/fish-lw-assignment_files\figure-html\unnamed-chunk-3-1.png',
  '/fish-lw-assignment_files\figure-html\unnamed-chunk-5-1.png',
  '/.posit/publish/Exploring Fish Length-Weight R-97GD.toml',
  '/.posit/publish/deployments/deployment-OJ6N.toml'
]
title = 'Exploring Fish Length-Weight Relationships'
